apply plugin: 'com.android.application'

android {
    ndkVersion "26.2.11394342"

    defaultConfig {
        applicationId 'com.flashphoner.wcsexample.webview_example'
        minSdkVersion 26
        compileSdk 33
        targetSdkVersion 33
        versionCode 2600001
        versionName "1.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.flashphoner.wcsexample'
    lint {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    // You must install or update the Support Repository through the SDK manager to use this dependency.
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}
